### ISSUE TITLE
Question re instance-purchase-option placement strategy

### ISSUE THREAD

**Issue by andriyfedorov** [aws-samples/ecs-refarch-mixed-mode#1]
Hi there,

Thank you very much for providing this reference architecture!

I would like to ask question re use of instance-purchase-option placement strategy.

In current setup you have 2 distinct clusters and 2 services that deployed in to different clusters: 

1) on-demand
2) spot

As you always deploying spot service in to spot cluster and you always deploying on-demand service in to on-demand cluster why do you use instance-purchase-option placement strategy? 

I understand that it would make sense to use it in case of one cluster that has on-demand and spot instances mixed together but when you have 2 separate clusters .... Am I missing something? :)

Thanks!

Andriy

**Comment by anshrma** [comment]
Hi @andriyfedorov - You are right, placement strategy is purely from illustration purpose and not used technically speaking.
